workflows:
  ios-auto-signing:
    name: iOS Auto Signing Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        DEVELOPMENT_TEAM: WT5TSJ49FM
      ios_signing:
        provisioning_profile: auto
        certificate: auto
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath $PWD/build/Runner.xcarchive \
                     archive \
                     DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
                     CODE_SIGN_STYLE=Automatic

          xcodebuild -exportArchive \
                     -archivePath $PWD/build/Runner.xcarchive \
                     -exportPath $PWD/build/ios/ipa \
                     -exportOptionsPlist ExportOptions.plist

      - name: Create ExportOptions.plist
        script: |
          cat <<EOF > ios/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>teamID</key>
              <string>${DEVELOPMENT_TEAM}</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <true/>
              <key>destination</key>
              <string>export</string>
            </dict>
          </plist>
          EOF
