workflows:
  ios-auto-signing:
    name: iOS Auto Signing Workflow
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.new.notificar
        DEVELOPMENT_TEAM: WT5TSJ49FM
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build and archive iOS app
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/Runner.xcarchive \
                     -destination 'generic/platform=iOS' \
                     -allowProvisioningUpdates \
                     archive

      - name: Export iOS App (.ipa)
        script: |
          cd ios
          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportPath build/ipa \
                     -allowProvisioningUpdates

    artifacts:
      - build/ipa/*.ipa
