workflows:
  ios-manual-signing:
    name: iOS Manual Signing
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.new.notificar
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Fix Podfile for Codemagic
        script: |
          cat > ios/Podfile <<EOF
          platform :ios, '13.0'

          ENV['FLUTTER_ROOT'] ||= File.expand_path('../flutter')
          load File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          target 'Runner' do
            flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
          end
          EOF

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build and archive iOS app without signing
        script: |
          flutter build ios --release --no-codesign
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath build/Runner.xcarchive \
                     -destination 'generic/platform=iOS' \
                     -allowProvisioningUpdates

      - name: Export .ipa without signing
        script: |
          cd ios
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>$DEVELOPMENT_TEAM</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.new.notificar</key>
              <string>Notificar</string>
            </dict>
          </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportPath build/ipa \
                     -exportOptionsPlist ExportOptions.plist \
                     -allowProvisioningUpdates

    artifacts:
      - build/ipa/*.ipa
