name: Build iOS IPA

on:
  workflow_dispatch:  # Permite iniciar o workflow manualmente

jobs:
  build:
    runs-on: macos-latest  # Vai rodar em um ambiente macOS

    steps:
      # Passo 1: Baixar o c처digo do reposit처rio
      - uses: actions/checkout@v4

      # Passo 2: Decodificar e instalar certificados e perfil de provis찾o
      - name: Decode Certificates
        run: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > dist.p12
          echo "$PROVISION_PROFILE_BASE64" | base64 --decode > profile.mobileprovision

      - name: Install Certificates
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import dist.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      # Passo 3: Construir o IPA
      - name: Build IPA
        run: |
          xcodebuild -workspace SeuApp.xcworkspace \
            -scheme SeuApp \
            -configuration Release \
            -archivePath $PWD/build/SeuApp.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/SeuApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build

      # Passo 4: Criar uma release no GitHub
      - name: Create GitHub Release
        id: release
        run: |
          # Cria uma nova release no GitHub
          TAG_NAME="v1.0.0"  # Defina a tag da release como quiser (por exemplo, vers찾o do app)
          RELEASE_NAME="Release v1.0.0"  # Nome da release
          BODY="Release do app iOS"
          
          RESPONSE=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"tag_name": "'"$TAG_NAME"'", "name": "'"$RELEASE_NAME"'", "body": "'"$BODY"'", "draft": false, "prerelease": false}' \
            https://api.github.com/repos/${{ github.repository }}/releases)
          
          echo "Release criada com sucesso"

      # Passo 5: Fazer o upload do IPA para a Release criada
      - name: Upload IPA to Release
        run: |
          # Faz o upload do IPA para a release no GitHub
          RELEASE_ID=$(echo $RESPONSE | jq -r .id)  # ID da release criada
          IPA_FILE_PATH="build/SeuApp.ipa"  # Caminho do arquivo IPA gerado

          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @"$IPA_FILE_PATH" \
            https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=SeuApp.ipa
          
          echo "IPA enviado para a Release"
