name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode Certificates
        run: |
          echo "$CERTIFICATE_BASE64" | base64 --decode > dist.p12
          echo "$PROVISION_PROFILE_BASE64" | base64 --decode > profile.mobileprovision

      - name: Install Certificates
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import dist.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA
        run: |
          xcodebuild -workspace SeuApp.xcworkspace \
            -scheme SeuApp \
            -configuration Release \
            -archivePath $PWD/build/SeuApp.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/SeuApp.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: app-ipa
          path: build/*.ipa
